### ISSUE TITLE
agoric amm dapp

### ISSUE THREAD

**Issue by danishyasin33** [robor-systems/agoric-amm#3]
### Description
Implement a front end for the Agoric AMM that is production ready and reflects well vs. comparable AMM applications that users are accustomed to.
The front end should make the following user actions available:

- Select input and output tokens -- Take into account tokens held by the user -- Take into account tokens with liquidity in the AMM -- Provide a good user experience for selecting deposit/withdrawal specific purses or using defaults
- View price for a given trade -- Dependent on trade size -- Show slippage vs. current price
- Trade on swap -- Set slippage tolerance
- Add liquidity to pool
- Remove liquidity from pool -- Partially remove liquidity -- Remove all liquidity
- Create a new liquidity pool
- Feel free to leverage any part of the existing React implementation.

### References
Uniswap: https://app.uniswap.org/#/swap
Sushiswap: https://app.sushi.com/swap
Current React Frontend: https://github.com/Agoric/dapp-treasury/blob/main/ui/src/components/Swap.jsx
Agoric AMM code: https://github.com/Agoric/agoric-sdk/tree/master/packages/zoe/src/contracts/multipoolAutoswap

### Agoric documentation: https://agoric.com/documentation/getting-started/

**Comment by danishyasin33** [comment]
Feedback from client: 
https://gist.github.com/samsiegart/37352966eedbf01f9e3e7f10d1f22200

TODOs: 
- Shifting percentage calculation to use Nat values instead of converting to float
- UI improvements including adding a 'MAX' button and improving UX throughout the app by improving state mgmt. 
- Checking out the bugs that Sam highlighted in the mentions gists. 
- Adding loaders and improving UX

Possible bugs (some already fixed): 
https://gist.github.com/samsiegart/8b4e8158987fea9c1466183dfd24ae89

**Comment by danishyasin33** [comment]
To run agoric-amm app: 
- switch to dapp branch for now, main is outdated, will update it soon. 
- use node stable version (14.17.0). Configure it using nvm by running nvm use stable 
- building agoric sdk/cli after selecting the right node version 
- run agoric amm dapp

**Comment by danishyasin33** [comment]
Bug: 
When you start a fresh wallet, the `Zoe fee` purse is empty. This causes the dapp to crash. This should be handled elegantly without the app crashing.

**Comment by Hussain-7** [comment]
## Update 20th December 2021
* Took some time to understand the code such that I can understand the flow of `context`.
* Worked on one of the Todos , added `Loader`  which show until the `assets`  are completely loaded.
* Also added a `Loader` for the time span when the `exchange rate calculation` is being done.
* The current state of bugs highlighted in https://gist.github.com/samsiegart/8b4e8158987fea9c1466183dfd24ae89, are as following:
   - [x] When adding liquidity, if I type in the RUN amount before selecting another token.
   - [x]  When adding liquidity, if I try to select the RUN purse before the app loads the purses.
   - [x] When adding liquidity, sometimes it appears to deselect my RUN purse (maybe something loads and it resets the input).
   - [x] When adding liquidity with 5 Agoric RUN currency and 0.17 BLD. 
*  Next I'll try to fix the left over bugs.
*  Pushed the code on `dapp-branch` in `agoric-amm` repo.

**Comment by aamnasarosh** [comment]
Dev Links:
- Updated Liquidity Positions flow: https://xd.adobe.com/view/5d01e0ba-ebcd-41a0-a229-6e5b0faed83c-0852/
-  Updated Liquidity flow: https://xd.adobe.com/view/5e3abb22-153f-4432-8a36-0551a271a2bd-0b69/
- Updated Swap flow: https://xd.adobe.com/view/a0b4fdda-de40-4ee2-9872-e3140b0c5d08-f5e7/

Link to the loader animation used: 
https://lottiefiles.com/share/z7smvali
https://assets8.lottiefiles.com/packages/lf20_z7smvali.json

Not sure about the point no. 1 and 2 mentioned in the feedback https://gist.github.com/samsiegart/37352966eedbf01f9e3e7f10d1f22200
Is this related to AMM or the other app used for wallet approval?

**Comment by Hussain-7** [comment]
## Update 21th December 2021
* Fixed a bug ; `Invalid value message` not showing even when input value > balance in the swap component.
* Added loaders to the liquidity component.
  1.  For the `asset loading`.
  2.  For the time when we `exchange rate` calculates.
  3.  For the time when `liquidity is being added` to the pool.
* Tried to improved state management so that refresh not required for view updated states. Still in progress had some issues but figured them out and will be able to fix them tomorrow.
* After this I will work on UI improvement according to the design which are left.
*  Pushed the code on `Hussain-branch` in `agoric-amm` repo.

**Comment by danishyasin33** [comment]
Please name branches more appropriately. Name it after a feature or something. For example, here it could be `ui-updates-#`, where # can be a number.

**Comment by aamnasarosh** [comment]
> Dev Links:
> 
> * Updated Liquidity Positions flow: https://xd.adobe.com/view/5d01e0ba-ebcd-41a0-a229-6e5b0faed83c-0852/
> * Updated Liquidity flow: https://xd.adobe.com/view/5e3abb22-153f-4432-8a36-0551a271a2bd-0b69/
> * Updated Swap flow: https://xd.adobe.com/view/a0b4fdda-de40-4ee2-9872-e3140b0c5d08-f5e7/
> 
> Link to the loader animation used: https://lottiefiles.com/share/z7smvali https://assets8.lottiefiles.com/packages/lf20_z7smvali.json
> 
> Not sure about the point no. 1 and 2 mentioned in the feedback https://gist.github.com/samsiegart/37352966eedbf01f9e3e7f10d1f22200 Is this related to AMM or the other app used for wallet approval?

**For point no. 2 mentioned in the feedback:**
Wallet connection and enable dapp flow: https://xd.adobe.com/view/7e382ba5-153f-44da-9d1d-d8c8948f7015-2b6b/

**Comment by Hussain-7** [comment]
## Update 22th December 2021
* Improved `state management` in the `liquidity component`. For dynamic changes in Ui.
* Updated `swap component` UI.
* Added `Action` and `Reducers` for managing wallet `wallet offers` state.
  1.  required for keeping track of offers sent to wallet.
  2.  For knowing when the two assets are actually swapped in wallet.
  3.  For better managing liquidity request sent to the wallet.
* Used the `reducers` to update the offers state in the `application context`.
* Loaders now working properly for Liquidity component as well.
* For tomorrow will work on left over UI and functionalities required for new additions in UI .
*  Pushed the code on `ui-fixes-1` in `agoric-amm` repo.

**Comment by Hussain-7** [comment]
## Update 23th December 2021
* Removed a `bug` :  switch asset icon in swap component caused error on being clicked before assets being selected.
* Added max button to `Swap` and `Liquidity` components such that when its clicked the value in input becomes the balance or the `max amount` of asset selected we have in the selected purse.
* After adding max button the code redundancy in liquidity and swap component increased ,so created a `custom input component` with all the functions related to input.
* Loading functionality added ,Using the `offers context` I added previously. The flow for assets swap when swap button clicked is :
  1. Swap offer request is sent to the wallet. 
  2. Dapp waits for swap offers to be accepted and loading icon shown on swap button.
  3. As soon as offers is accepted from wallet or rejected the corresponding icon with swapped or not swapped is reflected on the button.
*  Now that `swap flow` and `liquidity position flow` is completed.
* Tomorrow I'll work on some `Liquidity designs` left after that I'm on to `wallet plugin`.
*  Pushed the code on `ui-fixes-1` in `agoric-amm` repo.

**Comment by aamnasarosh** [comment]
Estimated time spent in sprint 9: 4.5 hrs

**Comment by Hussain-7** [comment]
## Update 24th December 2021
* When you start a fresh wallet, the Zoe fee purse is empty. This causes the dapp to crash. This is now  handled elegantly without the app crashing.
* Added toasts in `Swap` and `Liquidity` components such that when its clicked the toast will show the current progress of the offer.
* Still a few fixes left to the `liquidity component`.
* Worked on the wallet Plugin for `dapps` almost complete.
* Next on monday will complete UI testing and fixes as well as wallet plugin.
*  Pushed the code on `ui-fixes-1` in `agoric-amm` repo.

**Comment by danishyasin33** [comment]
TODOs:
- [ ] Move `Your Liquidity Positions` above `All Liquidity Positions`. 
- [ ] The liquidity positions can be handled better. They should be stored in the context for the first time and then retrieved asynchronously.  
- [ ] Create tool tip to explain slippage tolerance
- [ ] Replace icon of react app with agoric logo

**Comment by Hussain-7** [comment]
## Update 27th December 2021
Current Progress:
- [x] Move `Your Liquidity Positions` above `All Liquidity Positions`. 
- [ ] The liquidity positions can be handled better. They should be stored in the context for the first time and then retrieved asynchronously.  
- [ ] Some ui fixes left.
- [ ] Create tool tip to explain slippage tolerance
- [x] Replace icon of react app with agoric logo

Other Tasks:
* Completed the Wallet Plugin functionality and ui.
* Was stuck with some issue in wallet plugin was on it all the time.
* Will try to finish up left over tomorrow.
*  Pushed the code on `ui-fixes-1` in `agoric-amm` repo.

**Comment by Hussain-7** [comment]
## Update 28th December 2021
Current Progress:
* Was stuck with a problem in `agoric sdk` which was caused due to using filesystem of windows and linking `agoric` file in windows to bin in `wsl`.
* After hours of debugging and with some help was able to figure out this issue.
* After that reinstalled the `agoric sdk` in `wsl filesystem`.
* Cloned the `agoric-amm` and ran all preqs to run the app successfully
* Then worked on the `context refactoring` for the wallet plugin.
* Apart from this  adjusted toast positions now that wallet plugin is also in header.
* Will finish the todos left over from yesterday and the left overs tomorrow.

**Comment by danishyasin33** [comment]
Please make sure that all repos are cloned within the wsl filesystem and your code exists directly in the Linux subsystem. This improves performance as well. 
cc: @haseebasim

**Comment by Hussain-7** [comment]
## Update 29th December 2021
Task Completed:
- [x] The liquidity pools are now being cache after the first render of that `liquidity section component`.
- [x] The issue of `asset being unselected` on `rate calculation` in `Liquidity component` in add and remove liquidity is now fixed.
- [x] `Toast position` and its close btn bugs which was causing toast to not close is now fixed. Had an issue with toast version and now its fixed.
- [x] `Wallet approved` context was not being maintained on the `refresh`. So added  functionality for it to maintain wallet status even on refresh.
* Sorry for late ticket update. Probably it wasn't saved even though I updated last night.
* Code is been pushed to `ui-fixes-2` branch.

**Comment by Hussain-7** [comment]
## Update 30th December 2021
Task Completed:
- [x] `Balance` now updates in input div as soon as offer or transaction completes.
- [x] If `wallet disconnects` suddenly ,loading feature added so that no action could be performed.
- [x] Bugs fixed in `wallet connection context`, now wallet disconnect is also indicated in dapp.
- [x] Wallet plugin toast card improved.
- [x] Main cards  and header are now mobile responsive, toast are still to be mobile responsive
* Code is been pushed to `ui-fixes-2` branch.

**Comment by Hussain-7** [comment]
## Update 31th December 2021
Task Completed:
- [x] Now the the `liquidity remove` section also shows the pair to be removed on clicking liquidity remove from user liquidity pool.
- [x] `tool tip` added to liquidity to slippage icon in swap.
- [x] Added `state caching` to some components to improve performance. 
- [x] Made it somewhat mobile responsive.
- [x] Tested out the app for bugs but seems to be bug free at the moment. 
* Now I have no next task to work on.
* Code is been pushed to `ui-fixes-2` branch.

**Comment by danishyasin33** [comment]
There are certain issues with the existing implementation, apart from the issues that Sam has mentioned, take note of the following comments: 
- I attached @agoric linter again, make sure all the errors identified by this linter are resolved
- Resolve all issues pointed out by Sam 
- Make sure all caclulations are using AmountMath library instead of binary calculation. This issue would be apparent in Swap.jsx, ref: [AmountMath](https://agoric.com/documentation/ertp/guide/amount-math.html#amountmath-methods)
- Review #4 and evaluate to make sure no unnecessary changes are present.

**Comment by danishyasin33** [comment]
Important resource for understanding ratio manipulation: 
https://agoric.com/documentation/zoe/api/contract-support/ratio-math.html

**Comment by Hussain-7** [comment]
## Update 13th January 2022
Some of issues resolved pointed by Sam:
- [x] The `notifications` seemed to make a horizontal scroll-bar flicker on the page, that is now fixed.
- [x] After closing and reopening the panel, the `all liquidity positions` section seems to be stuck in a loading state. That is fixed for the case when user liquidities already present.
- [x] The `your liquidity positions` seemed to briefly show `no positions` between the loading and loaded state.
- [x] On clicking of `remove` and `add` button in liquidity section the section should close

Other Issue:
- [x] Resolved all the linter issues.
- [x] Review UI rebased #4 and evaluated to make sure no unnecessary changes are need now.

* Code is been pushed to `ui-rebased` branch.

**Comment by Hussain-7** [comment]
## Update 14th January 2022
Issues fixed:
- [x] Open close Liquidity pools section on add and subtract button click
- [x] Liquidity Pools were being on loading state when we closed on opening the `liquidity section` again after the pools loaded once. This issue is fixed now.
- [x] Selecting a liquidity pools with some asset whose purse was not in the wallet   gave some errors and app crashes. Fixed this with proper error shown
- [x]  Also, it doesn't seem to let me select my second (non-RUN) purse when removing liquidity, and the `confirm withdrawal` button still appears disabled but clicking it throws an error.
- [ ] Make sure all calculations are using AmountMath library instead of binary calculation. This issue would be apparent in Swap.jsx, ref: AmountMath
- all issue apart from one above are fixed
- Have a good understanding of amountMath functions now but can't see where the functions are not already been used
* Code is been pushed to `ui-rebased` branch.

**Comment by Hussain-7** [comment]
## Update 15th January 2022
#### Issue left:
- [x] Have checked the swap flow multiple times and from the `input value changes` till the `exchange rate` calculation `Amount` is being used everywhere. Just to maintain state the Nat or decimal values are being used.
- [ ] slippage conversion to amount. 

#### Progress:
- Read all the content available related to `ERTP` in the agoric documentation
- Read thoroughly about `Zoe` and understood the framework. Figured out the contracts that are currently being used in the agoric-amm.
- Next will try to understand the `Autoswap` and `ConstantProduct AMM`  contracts used in agoric-amm for better understanding.
- Gone through a very handy `glossary` in the agoric documentation that provided meaning for all new terms used.
- Covered most documentation part today .
#### Todo's next:
- Slippage conversion to amount.
- Will implement a `sample contract` and use in agoric-amm for testing.

**Comment by Hussain-7** [comment]
## Update 16th January 2022
#### Issue fixed today:
- Created a `custom Tab component` to fix the following issue
- [x] The "Add" button in the side-panel only seems to work if the center panel is actively on the "Add" tab. It should ideally still work and switch from the remove tab to the add tab if necessary. Also for remove button. 
#### Progress:
- Read through the `Agoric Wallet` documentation to be able to debug the issue that occurred due to sdk update. Got a deep understanding of the `wallet bridge protocol`.
- Also went through the already provided sample contracts in the agoric-amm to get a deep understanding of `contract structure`.
- Code is been pushed to `ui-rebased` branch.

**Comment by danishyasin33** [comment]
Completed for now, requires no further action.
